import { type VimState, Mode } from '../../types';

export const INITIAL_LINES = [
  'Welcome to Vim Playground!',
  '---------------------------',
  '[Navigation]',
  '  h,j,k,l : Basic movement',
  '  w,b,e   : Word movement',
  '  gg, G   : Top / Bottom of file',
  '  {N}gg/G : Jump to line N',
  '  Ctrl+u/d: Half page up/down',
  '  %       : Match bracket () {} []',
  '  $, _    : End/Start of line',
  '  f/F+char: Find char forward/backward',
  '',
  '[Editing]',
  '  i, a    : Insert (before/after)',
  '  o, O    : Open line (below/above)',
  '  dd, yy  : Delete / Yank line',
  '  cc      : Change line',
  '  r+char  : Replace character',
  '  J       : Join lines',
  '  p       : Paste',
  '  u, ^r   : Undo / Redo',
  '',
  '[Visual & Search]',
  '  v, V, ^v: Visual char/line/block',
  '  x, d    : Delete selection',
  '  y       : Yank selection',
  '  ~, u, U : Case toggle/lower/upper',
  '  <, >    : Indent/Outdent',
  '  I, A    : Block Insert (Visual Block)',
  '  J       : Join selection',
  '  r+char  : Replace selection',
  '  /query  : Search (Enter to find)',
  '  n, N    : Next / Prev match',
  '',
  '// Happy Vimming!',
];

export const INITIAL_STATE: VimState = {
  lines: INITIAL_LINES,
  cursor: { line: 0, col: 0 },
  mode: Mode.NORMAL,
  visualStart: null,
  clipboard: null,
  waitingForChar: false,
  findDirection: null,
  commandBuffer: '',
  searchQuery: '',
  searchMatchIndex: null,
  commandBar: null,
  visualBlock: null,
  history: [],
  historyIndex: -1,
};
